In [10]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [11]:
train_data = pd.read_csv("/train_data.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
test_data = pd.read_csv("/test_data.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [13]:
from sklearn.ensemble import RandomForestClassifier

#Saved all Survived from train_data
y = train_data["Survived"]

#Select four column as consider the feature for train and prediction

features = ["Pclass", "Sex", "SibSp", "Parch", "Embarked"]
#Store the train_data selected features
X = pd.get_dummies(train_data[features])

#Store the test_data selected features
X_test = pd.get_dummies(test_data[features])

#use the sklearn -> RandomForestClassifier model with epoch, depth, and random state

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
#Train the model with train_data feature and survived people from train data
model.fit(X, y)
#Now time to do perdiction from test data as per features who survived
predictions = model.predict(X_test)
#Store the ouput as DataFrame for test data as per prediction for Survived
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
# Store the output in submission file
output.to_csv('submission.csv', index=False)
print(output)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

# New Section